app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
// Route::get('industrial', ['uses'=>'HomeController@industrial', 'as'=>'industrial']);

Route::group(['before'=>'csrf'], function(){
	Route::post('/login', array(
			'as'=> 'login.post',
			'uses'=> 'LoginController@store'
	));
	Route::post('/ajax/checkout/save', array(
			'as'=> 'checkout.save.post',
			'uses'=> 'CheckoutController@store'
	));
	Route::post('/user/register', array(
			'as'=> 'user.register',
			'uses'=> 'AjaxController@registerUser'
	));
});


Route::post('/check/user/email', array(
		'as' => 'check.user.email',
		'uses' => 'AjaxController@checkEmailAddress'
	));

Route::post('/get/size/legend', array(
		'as' => 'size.legend',
		'uses' => 'AjaxController@getSizeLegend'
	));

Route::post('/user/popup/view', array(
		'as' => 'user.popup.view',
		'uses' => 'UsersController@viewPopupUser'
	));

Route::post('/user/popup/view/gallery', array(
		'as' => 'user.popup.view.gallery',
		'uses' => 'UsersController@viewPopupUserGallery'
	));

Route::post('/page/view/gallery', array(
		'as' => 'page.view.gallery',
		'uses' => 'AjaxController@loadPageGallery'
	));

Route::post('/footbook/selection', array(
		'as' => 'footbook.selection',
		'uses' => 'AjaxController@loadSelection'
	));

Route::post('/checkout/summary', array(
		'as' => 'checkout.summary',
		'uses' => 'AjaxController@loadCheckoutRightSide'
	));

Route::post('/preview/save', array(
		'as' => 'preview.save',
		'uses' => 'AjaxController@loadPreviewRight'
	));

Route::post('/checkout/gallery/selection', array(
		'as' => 'checkout.gallery.selection.right',
		'uses' => 'AjaxController@loadMyGallerySelectionRight'
	));

Route::post('/destroy', array(
		'as' => 'logout.frontend',
		'uses' => 'LoginController@destroy'
	));

Route::post('/auth/check/login', array(
		'as' => 'auth.check.login',
		'uses' => 'AjaxController@checkAuth'
	));

Route::group(['prefix'=>'admin'], function(){

	Route::get('/', function() {
		if (Auth::guest()) {
			return redirect()->to('/admin/auth/login');
		}
		else {
			return redirect()->route('admin.dashboard');
		}
	});
	Route::group(['middleware' => 'auth'], function(){
		Route::get('dashboard', ['uses'=>'HomeController@admin', 'as'=>'admin.dashboard']);

		Route::get('/items/search', ['uses'=>'ItemsController@search', 'as'=>'admin.items.search']);
		Route::resource('items', 'ItemsController');
		Route::get('/items/{id}/delete', ['uses'=>'ItemsController@destroy', 'as'=>'admin.items.destroy']);

		Route::resource('users', 'UsersController');
		Route::get('/users/{id}/delete', ['uses'=>'UsersController@destroy', 'as'=>'admin.users.destroy']);

		Route::get('/themes/search', ['uses'=>'ThemesController@search', 'as'=>'admin.themes.search']);
		Route::resource('themes', 'ThemesController');
		Route::get('/themes/{id}/delete', ['uses'=>'ThemesController@destroy', 'as'=>'admin.themes.destroy']);

		Route::resource('products', 'ProductsController');
		Route::get('/products/{id}/delete', ['uses'=>'ProductsController@destroy', 'as'=>'admin.products.destroy']);

		Route::get('/roles/permissions', ['uses'=>'RolesController@editPermissions', 'as'=>'admin.permissions.edit']);
		Route::post('/roles/permissions', ['uses'=>'RolesController@updatePermissions', 'as'=>'admin.permissions.update']);
		Route::resource('roles', 'RolesController');

		Route::get('/checkout/search', ['uses'=>'CheckoutController@search', 'as'=>'admin.checkout.search']);
		Route::resource('checkout', 'CheckoutController');
		Route::get('/checkout/{id}/delete', ['uses'=>'CheckoutController@destroy', 'as'=>'admin.checkout.destroy']);

	});
	

	Route::controllers([
		'auth' => 'Auth\AuthController',
		'password' => 'Auth\PasswordController',
	]);


});

Route::post('/products/save', ['uses'=>'ProductsController@store', 'as'=>'products.store']);

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Footbook Admin</title>

	<link href="{{ asset('/admin-assets/css/app.css') }}" rel="stylesheet">
	<link href="{{ asset('/admin-assets/css/admin.css') }}" rel="stylesheet">

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
	<script src="{{ asset('/admin-assets/js/bootbox.min.js') }}"></script>
	<script src="{{ asset('/admin-assets/js/admin.js') }}"></script>

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/admin"><img src="/images/logo.png" alt="" style="max-height: 40px; position: relative; top: -8px;"/></a>
			</div>

			<style type="text/css">
				.dropdown-menu > li > a {
					font-weight: 100;
				}
			</style>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				@if (!Auth::guest())
				<ul class="nav navbar-nav">
					@if(Auth::user()->can('manage_product'))
					<li>
						<a href="{{ route('admin.products.index') }}">
							Products
						</a>
					</li>
					@endif

					@if(Auth::user()->can('manage_orders'))
					<li class="dropdown"><a href="{{ route('admin.items.index') }}" class="dropdown-toggle" data-toggle="dropdown">Orders <b class="caret"></b></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{{ route('admin.checkout.index') }}">View Orders</a></li>
							<!-- <li><a href="{{ route('admin.checkout.create') }}">Cancelled Orders</a></li> -->
						</ul>
					</li>
					@endif

					@if(Auth::user()->can('manage_items'))
					<li class="dropdown"><a href="{{ route('admin.items.index') }}" class="dropdown-toggle" data-toggle="dropdown">Items <b class="caret"></b></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{{ route('admin.items.index') }}">View Items</a></li>
							<li><a href="{{ route('admin.items.create') }}">Add Item</a></li>
						</ul>
					</li>
					@endif
					<!-- <li class="dropdown"><a href="{{ route('admin.themes.index') }}" class="dropdown-toggle" data-toggle="dropdown">Themes <b class="caret"></b></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="{{ route('admin.themes.index') }}">View Themes</a></li>
							<li><a href="{{ route('admin.themes.create') }}">Add Themes</a></li>
						</ul>
					</li> -->
					@if(Auth::user()->can('manage_users') || Auth::user()->can('manage_roles') || Auth::user()->can('manage_role_permission'))
					<li class="dropdown"><a href="{{ route('admin.users.index') }}" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
						<ul class="dropdown-menu" role="menu">
							@if(Auth::user()->can('manage_users'))
							<li><a href="{{ route('admin.users.index') }}">View Users</a></li>
							<li><a href="{{ route('admin.users.create') }}">Add Users</a></li>
							<li class="divider"></li>
							@endif
							@if(Auth::user()->can('manage_roles'))
							<li><a href="{{ route('admin.roles.index') }}">View Roles</a></li>
							<li><a href="{{ route('admin.roles.create') }}">Add Roles</a></li>
							@endif
							@if(Auth::user()->can('manage_role_permission'))
							<li><a href="{{ route('admin.permissions.edit') }}">Edit Permissions</a></li>
							@endif
						</ul>
					</li>
					@endif
				</ul>
				@endif

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/admin/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/admin/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->email }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/admin/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>
	@yield('content')

</body>
</html>

resources/views/footbook-checkout-right.blade.php
<h2>Summary</h2>
<form id="checkout-form">
  {!! Form::token() !!}
  <input type="hidden" name="product_id" id="checkout_product_id">
  <table>
    <tr>
      <th>Item</th>
      <th>Price</th>
    </tr>
    @if(isset($items['items']['print_design']))
    <tr>
      <td>Print Design</td>
      <td><span>PHP</span> {{ $items['items']['print_design']['price'] }}</td>
    </tr>
    @endif
    @if(isset($items['items']['strap_style']))
    <tr>
      <td>Strap</td>
      <td><span>PHP</span> {{ $items['items']['strap_style']['price'] }}</td>
    </tr>
    @endif
    @if(isset($items['items']['accessories']))
      @foreach ($items['items']['accessories'] as $key=>$item)
      <tr>
        <td>{{ $item['item_name'] }}</td>
        <td><span>PHP</span> {{ $item['price'] }}</td>
      </tr>
      @endforeach
    @endif
  </table>
  <table class="popup-checkout-subtotal">
    <tr>
      <td>Subtotal</td>
      <td><span>PHP</span> {{ $total }}.00
      <input type="hidden" id="unit_total_price" value="{{ $total }}" name="unit_total_price"></td>
    </tr>
  </table>

  <table id="orders_wrapper_counter" class="popup-checkout-grandtotal">
    <tr>
      <td  colspan="0">SIZE</td>
      <td>
        <select id="item_size">
          <option value="6">6</option>
          <option value="6.5">6.5</option>
          <option value="7">7</option>
          <option value="7.5">7.5</option>
          <option value="8">8</option>
          <option value="8.5">8.5</option>
          <option value="9">9</option>
          <option value="9.5">9.5</option>
          <option value="10">10</option>
          <option value="10.5">10.5</option>
          <option value="11">11</option>
          <option value="11.5">11.5</option>
          <option value="12">12</option>
        </select>
      </td>
      
      <td> 
        <select id="item_size_country">
          <option value="US">US</option>
          <option value="UK">UK</option>
          <option value="EU">EU</option>
        </select>
      </td>
      <td>
        <a href="javascript:(void)" class="btn btn-blue btn-size-legend">LEGEND </a>
      </td>
    </tr>
    </table> 
    <table id="qty-wrapper" style="margin-bottom: 2px;">
    <tr>
  
          <td style="width:98px;" class="quantity2">QUANTITY </td>

          <td>
            <input type="text" id="item_qty" value="1" style="width:45px; margin-top:6px;">
          </td>
             
          <td><button type="button" id="add_item_count" class="btn btn-green add-btn">+</button></td>
    
    </tr>
    </table>
    <table>
    <tr>
      <td colspan="3">Total Quantity</td>
      <td colspan="3"><span id="total_qty">0</span></td>
    </tr>
    <tr>
   
      <td colspan="3">Grand Total</td>
      
      <td colspan="3"><span>PHP</span> <span id="grand_total">0.00</span><input type="hidden" name="grand_total" id="grand_total_placeholder"></td>
    </tr>
  
  </table>
</form>
<script>
$(function(){
  getProductID();
  var count = 0;
  $("#add_item_count").on('click', function(){
    var item_size = $("#item_size").val();
    var item_qty  = parseInt($("#item_qty").val());
    var item_size_country = $("#item_size_country").val();
    var duplicates = false;
    var tmp_ctr = 0;
    // check if there is already an item size for the newly added.
    $(".order_sizes").each(function(){
      if($(this).val() == item_size && $(this).data('country') == item_size_country){
        duplicates = true;
        tmp_ctr = $(this).data("counter");
      }
    });
    if(item_qty > 0 && !duplicates){
      // set ids 
      var wrapper       = "order_wrapper_"+count;
      var item_size_id  = "order_size_"+count;
      var item_qty_id   = "order_qty_"+count;
      var item_qty_id_span = "order_qty_span_"+count;
      // set name
      var item_size_name          = "order[item]["+count+"][size]";
      var item_size_country_name  = "order[item]["+count+"][country]";
      var item_qty_name           = "order[item]["+count+"][qty]";

      var html = "<table id='"+wrapper+"'>"
      html      += "<tr>";
      html      += "<td>SIZE:</td>";
      html      += "<td><input type='hidden' data-counter='"+count+"' data-country='"+item_size_country+"' class='order_sizes' name='"+item_size_name+"' id='"+item_size_id+"' value='"+item_size+"'>"+item_size+"</td><td>" + item_size_country + "<input type='hidden' value='"+item_size_country+"' name='"+item_size_country_name+"'></td>";
      html      += "<td>QTY:</td>";
      html      += "<td><input type='hidden' name='"+item_qty_name+"' class='order_qty' id='"+item_qty_id+"' value='"+item_qty+"'><span id='"+item_qty_id_span+"''>"+item_qty+"</span></td>";
      html      += "<td><button type='button' class='btn btn-red btn-remove' onclick='removeOrderItem("+count+")'>-</button> </td>";
      html      += "</tr>";
       html      += "</table>";

      $(html).insertAfter($("#qty-wrapper"));
      count++;
      $("#item_qty").val(1);
    }else if(item_qty > 0 && duplicates){
      var tmp_item_qty = $("#order_qty_"+tmp_ctr).val();
      var tmp_total = parseInt(tmp_item_qty) + parseInt(item_qty);
      $("#order_qty_"+tmp_ctr).val(tmp_total);
      $("#order_qty_span_"+tmp_ctr).html(tmp_total);
      $("#item_qty").val(1);
    } else {
      alert("Quality must be higher than 0");
    }
    countAndCompute();
  });
});

function countAndCompute(){
  var qty = 0;
  $(".order_qty").each(function(){
    qty += parseInt($(this).val());
  });
  $("#total_qty").html(qty);
  var unit = parseFloat($("#unit_total_price").val());
  var grand_total = qty * unit;
  $("#grand_total").html(addCommas(grand_total.toFixed(2)));
  $("#grand_total_placeholder").val(grand_total.toFixed(2));
}

function addCommas(nStr)  // Add Comma to Price (Numbers)
{
  nStr += '';
  x = nStr.split('.');
  x1 = x[0];
  x2 = x.length > 1 ? '.' + x[1] : '';
  var rgx = /(\d+)(\d{3})/;
  while (rgx.test(x1)) {
    x1 = x1.replace(rgx, '$1' + ',' + '$2');
  }
  return x1 + x2;
}
function getProductID(){
  var product_id = $("#product_id").val();
  $("#checkout_product_id").val(product_id);
}

function removeOrderItem(counter){
  $("#order_wrapper_"+counter).remove();
  countAndCompute();
}
</script>

resources/views/footbook-selection.blade.php
<link href='//fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="style.css">
<script src="js/jquery.min.js"></script>
<script src="js/app.js"></script>
<div class="newdesign">
    <div class="clear"></div>
      <h3>Print Design</h3>

        <ul id="print_design" class="js-carousel options-design-print-design  newprint">

          @foreach ($items['Print Design'] as $item)
            <li><a data-item-id="{{ $item->id }}" data-image="{{ asset($item->texture_path) }}"></a></li>
          @endforeach
        </ul> 
        <div class="options-design-upload">
          <a class="btn btn-orange btn-small btn-upload-move-up"><span class="glyphicon glyphicon-arrow-up"></span></a><a class="btn btn-orange btn-small btn-upload-move-down"><span class="glyphicon glyphicon-arrow-down"></span></a><a class="btn btn-orange btn-small btn-upload-move-left"><span class="glyphicon glyphicon-arrow-left"></span></a><a class="btn btn-orange btn-small btn-upload-move-right"><span class="glyphicon glyphicon-arrow-right"></span></a><br><a class="btn btn-orange btn-small btn-upload-zoom-in"><span class="glyphicon glyphicon-zoom-in"></span></a><a class="btn btn-orange btn-small btn-upload-zoom-out"><span class="glyphicon glyphicon-zoom-out"></span></a><a class="btn btn-orange btn-small btn-mirror">Mirror</a>
          <!--a.btn.btn-orange.btn-small.btn-remove-upload Remove-->
        </div>
  <div class="options-style">
    <h3>Strap Style</h3>
    <ul class="js-carousel options-style-strap sole" id="strap_style">
    @foreach ($items['Strap'] as $item)
      <li {{ $item->item_id == "men3c" ? "class=active" : "" }}><a class="my-style-strap" data-item-id="{{ $item->id }}" data-basename="{{ $item->item_id }}"><img src="{{ asset($item->texture_path) }}" style="max-height: 90%;"></a></li>
    @endforeach
    </ul>
  <h3>Sole Style</h3>
    <ul class="js-carousel sole">
      <li class="active"><a>Sole 1</a></li>
      <li><a>Sole 2</a></li>
      <li><a>Sole 3</a></li>
    </ul>
    <ul style="top: 15px;" class="options-style-color active">
      <li class="colortest active"><a data-color="#0A4436" data-basename="men3c" data-colorname="green">Green</a></li>
      <li class="colortest"><a data-color="#808285" data-basename="men3c" data-colorname="grey">Grey</a></li>
      <li class="colortest"><a data-color="#000000" data-basename="men3c" data-colorname="black">Black</a></li>
      <li class="colortest"><a data-color="#FD6B35" data-basename="men3c" data-colorname="orange">Orange</a></li>
      <li class="colortest"><a data-color="#F6B332" data-basename="men3c" data-colorname="yellow">Yellow</a></li>
      <li class="colortest"><a data-color="#D0112B" data-basename="men3c" data-colorname="red">Red</a></li>
    </ul>
    <ul id="sole_color" style="top: 190px;" class="options-style-color">
      <li class="active"><a data-color="#FFFFFF">White</a></li>
      <li><a data-color="#808285">Grey</a></li>
      <li><a data-color="#000000">Black</a></li>
      <li><a data-color="#0A4436">Green</a></li>
      <li><a data-color="#FD6B35">Orange</a></li>
      <li><a data-color="#F6B332">Yellow</a></li>
      <li><a data-color="#D0112B">Red</a></li>
    </ul>
    <div class="clear"></div>
  </div>
  <h3>Strap Accessories</h3>
    <ul class="js-carousel options-strap-accessories newprint">
    @foreach ($items['Accessory'] as $item)
      <li><a data-price="{{ number_format($item->price, 2) }}"><img src="{{ asset($item->texture_path) }}"></a></li>
    @endforeach
    </ul>
  </div>

  <script>
    $(function(){
      $('.js-carousel').owlCarousel({
        items: 4,
        navigation: true,
        pagination: false,
        responsive: false,
      });
    });
  </script>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">DASHBOARD</div>
                    <div class="alert alert-success alert-dismissible" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      You have <strong>{!! $new_order !!}</strong> new Order(s)! click <a href="{{ route('admin.checkout.index') }}">here</a> to view.
                    </div>
                <div class="panel-body fb-dashboard">
                    @if(Auth::user()->can('manage_product'))
                    <a href="{{ route('admin.products.index') }}">
                        <img src="{{ asset('/admin-assets/img/icon-gallery.png')}}" alt=""/>
                        Product Management
                    </a>
                    @endif

                    @if(Auth::user()->can('manage_orders'))
                    <a href="{{ route('admin.checkout.index') }}">
                        <img src="{{ asset('/admin-assets/img/icon-prod.png')}}" alt=""/>
                        Orders Management
                    </a>
                    @endif

                    @if(Auth::user()->can('manage_items'))
                    <a href="{{ route('admin.items.index') }}">
                        <img src="{{ asset('/admin-assets/img/icon-prod.png')}}" alt=""/>
                        Item Management
                    </a>
                    @endif
                    <!-- <a href="{{ route('admin.themes.index') }}">
                        <img src="{{ asset('/admin-assets/img/icon-theme.png')}}" alt=""/>
                        Theme Management
                    </a> -->

                    @if(Auth::user()->can('manage_users'))
                    <a href="{{ route('admin.users.index') }}">
                        <img src="{{ asset('/admin-assets/img/icon-user.png')}}" alt=""/>
                        User Management
                    </a>
                    @endif

                    @if(Auth::user()->can('manage_role_permission') || Auth::user()->can('manage_roles'))
                    <a href="{{ route('admin.roles.index') }}">
                        <img src="{{ asset('/admin-assets/img/icon-role.png')}}" alt=""/>
                        Role Access Management
                    </a>
                    @endif
                </div>
			</div>
		</div>
	</div>
</div>
@endsection