app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
// Route::get('industrial', ['uses'=>'HomeController@industrial', 'as'=>'industrial']);

Route::group(['before'=>'csrf'], function(){
	Route::post('/login', array(
			'as'=> 'login.post',
			'uses'=> 'LoginController@store'
	));
	Route::post('/ajax/checkout/save', array(
			'as'=> 'checkout.save.post',
			'uses'=> 'CheckoutController@store'
	));
	Route::post('/user/register', array(
			'as'=> 'user.register',
			'uses'=> 'AjaxController@registerUser'
	));
});


Route::post('/check/user/email', array(
		'as' => 'check.user.email',
		'uses' => 'AjaxController@checkEmailAddress'
	));

Route::post('/get/size/legend', array(
		'as' => 'size.legend',
		'uses' => 'AjaxController@getSizeLegend'
	));

Route::post('/user/popup/view', array(
		'as' => 'user.popup.view',
		'uses' => 'UsersController@viewPopupUser'
	));

Route::post('/user/popup/view/gallery', array(
		'as' => 'user.popup.view.gallery',
		'uses' => 'UsersController@viewPopupUserGallery'
	));

Route::post('/page/view/gallery', array(
		'as' => 'page.view.gallery',
		'uses' => 'AjaxController@loadPageGallery'
	));

Route::post('/footbook/selection', array(
		'as' => 'footbook.selection',
		'uses' => 'AjaxController@loadSelection'
	));

Route::post('/checkout/summary', array(
		'as' => 'checkout.summary',
		'uses' => 'AjaxController@loadCheckoutRightSide'
	));

Route::post('/preview/save', array(
		'as' => 'preview.save',
		'uses' => 'AjaxController@loadPreviewRight'
	));

Route::post('/checkout/gallery/selection', array(
		'as' => 'checkout.gallery.selection.right',
		'uses' => 'AjaxController@loadMyGallerySelectionRight'
	));

Route::post('/destroy', array(
		'as' => 'logout.frontend',
		'uses' => 'LoginController@destroy'
	));

Route::post('/auth/check/login', array(
		'as' => 'auth.check.login',
		'uses' => 'AjaxController@checkAuth'
	));

Route::group(['prefix'=>'admin'], function(){

	Route::get('/', function() {
		if (Auth::guest()) {
			return redirect()->to('/admin/auth/login');
		}
		else {
			return redirect()->route('admin.dashboard');
		}
	});
	Route::group(['middleware' => 'auth'], function(){
		Route::get('dashboard', ['uses'=>'HomeController@admin', 'as'=>'admin.dashboard']);

		Route::get('/items/search', ['uses'=>'ItemsController@search', 'as'=>'admin.items.search']);
		Route::resource('items', 'ItemsController');
		Route::get('/items/{id}/delete', ['uses'=>'ItemsController@destroy', 'as'=>'admin.items.destroy']);

		Route::resource('users', 'UsersController');
		Route::get('/users/{id}/delete', ['uses'=>'UsersController@destroy', 'as'=>'admin.users.destroy']);

		Route::get('/themes/search', ['uses'=>'ThemesController@search', 'as'=>'admin.themes.search']);
		Route::resource('themes', 'ThemesController');
		Route::get('/themes/{id}/delete', ['uses'=>'ThemesController@destroy', 'as'=>'admin.themes.destroy']);

		Route::resource('products', 'ProductsController');
		Route::get('/products/{id}/delete', ['uses'=>'ProductsController@destroy', 'as'=>'admin.products.destroy']);

		Route::get('/roles/permissions', ['uses'=>'RolesController@editPermissions', 'as'=>'admin.permissions.edit']);
		Route::post('/roles/permissions', ['uses'=>'RolesController@updatePermissions', 'as'=>'admin.permissions.update']);
		Route::resource('roles', 'RolesController');

		Route::get('/checkout/search', ['uses'=>'CheckoutController@search', 'as'=>'admin.checkout.search']);
		Route::resource('checkout', 'CheckoutController');
		Route::get('/checkout/{id}/delete', ['uses'=>'CheckoutController@destroy', 'as'=>'admin.checkout.destroy']);

	});
	

	Route::controllers([
		'auth' => 'Auth\AuthController',
		'password' => 'Auth\PasswordController',
	]);


});

Route::post('/products/save', ['uses'=>'ProductsController@store', 'as'=>'products.store']);

app/Http/Controllers/CheckoutController.php
<?php namespace App\Http\Controllers;

use App\Item;
use App\ItemProperty;
use App\Order;
use App\OrderItem;
use App\Theme;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Storage;
use Image;
use Auth;

class CheckoutController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');

		if(!Auth::user()->can('view_admin')){
			abort(403, 'Unauthorized action. Please contact your Administrator.');
		}
		
		if(!Auth::user()->can('manage_items')){
			abort(403, 'Unauthorized action. Please contact your Administrator.');
		}
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$items = Order::orderBy('created_at','desc')->paginate(10);
		return view('checkout.index', compact('items'));
	}


	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function search(Request $request)
	{
		$query = $request->input('q');
		$items = Order::search($query)->paginate(10);
		$request->flash();

		return view('checkout.index', compact('items', 'query'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$data['itemTypesList'] = $this->lookupSelect('item_type');
		$data['AvailabilityTypesList'] = $this->lookupSelect('availability');
		$data['GenderAvailabilityTypesList'] = $this->lookupSelect('age_demographic');
		$data['themesList'] = Theme::get()->lists('name', 'id');
		$data['itemThemes'] = null;
		return view('items.create', $data);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param StoreItemRequest
	 * @return Response
	 */
	public function store(Request $request)
	{
		$input = $request->all();
		// dd($input);
		$order 					= new Order;
		$order->order_id 		= Order::generateNewOrderNumber();
		$order->amount 			= (float) $input['grand_total'];
		$order->payment_mode 	= 1;
		$order->ip 				= $request->ip();
		$order->save();

		foreach ($input['order']['item'] as $key => $value) {

			// dd($value['country']);
			$order->items()->save(new OrderItem([
					'product_id' 	=> $input['product_id'],
					'size' 			=> $value['size'],
					'country_size' 	=> $value['country'],
					'quantity' 		=> $value['qty'],
					'amount' 		=> (float) $input['unit_total_price'],
					'total_amount' 	=> (int) $value['qty'] * (float) $input['unit_total_price']
					]));
		}

		return $order->order_id;
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$item = Order::find($id)->load(['items']);
		return view('checkout.show', compact('item'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		
		$item = Order::find($id)->load(['items']);
		return view('checkout.edit', compact('item'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Request $request)
	{
		$item = Order::with(['items'])->find($id);
		$input = $request->all();

		$item->o_status = $input['o_status'];
		$item->save();

		return redirect()->route('admin.checkout.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Order::find($id)->delete();

		return redirect()->route('admin.checkout.index');
	}

}

resources/views/checkout/edit.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			{!! Breadcrumbs::render() !!}
			<div class="panel panel-default">
				<div class="panel-heading">EDIT ORDER</div>

				<div class="panel-body">

                    @include('errors.list')

                    {!! Form::model($item, [ 'method' => 'PATCH', 'route' => [ 'admin.checkout.update', $item["id"] ], 'class' => 'form-horizontal']) !!}
						@include('checkout.form')
						<div class="col-md-4 col-md-offset-4">
					        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
					    	<a href="{{ route('admin.items.show', [$item['id']]) }}" class="btn btn-primary">Cancel</a>
					    </div>
                    {!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/checkout/form.blade.php
<link href="{{ asset('/admin-assets/css/bootstrap-colorpicker.min.css') }}"  rel="stylesheet">
<script src="{{ asset('/admin-assets/js/bootstrap-colorpicker.min.js') }}"></script>
<div class="row">
    <fieldset>

    <!-- Text input-->
    <!-- <div class="form-group">
      <label class="col-md-4 control-label" for="item_id">Item ID</label>
      <div class="col-md-4">
      
      </div>
    </div> -->
    <input type="hidden" name="order_id" value="{{ $item->id }}">
    <!-- SELECT -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="type">Order Status</label>
      <div class="col-md-4">
        {!! Form::select('o_status', [''=>'Please Select','New'=>'New','Processing'=>'Processing','Delivering' => 'Delivering','Done'=>'Done','Cancelled' => 'Cancelled'], null, ['class'=>'form-control', 'required', 'id'=>'o_status']) !!}
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-4 control-label" for="type">Order #</label>
      <div class="col-md-4">
        {!! Form::text('order_num', $item['order_id'], ['class'=>'form-control input-md', 'disabled']) !!}
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-4 control-label" for="type">Amount</label>
      <div class="col-md-4">
        {!! Form::text('amount', 'PHP ' . number_format($item['amount'],2,'.',',') , ['class'=>'form-control input-md', 'disabled']) !!}      </div>
    </div>

    <div class="form-group">
      <label class="col-md-4 control-label" for="type">Payment Mode</label>
      <div class="col-md-4">
        {!! Form::text('payment_mode', ($item['payment_mode'] == 1 ? "CASH" : "CHEQUE"), ['class'=>'form-control input-md', 'disabled']) !!}
      </div>
    </div>
    
    <h4 style="text-align: center;">
      Order Items: 
      @foreach ($item['items'] as $key => $value)
        {{ App\Product::find($value->product_id)->title }}
        <?php break; ?>
      @endforeach
    </h4>
    <center>
      <table class="table table-bordered" style="width: 80%;text-align: center;">
        <thead>
          <th style="text-align: center;">Size</th>
          <th style="text-align: center;">Quantity</th>
          <th style="text-align: center;">Amount</th>
          <th style="text-align: center;">Total Amount</th>
        </thead>
        <tbody>
          @foreach ($item['items'] as $key => $value)
          <tr>
            <td>{{ $value->size }} {{ $value->country_size }}</td>
            <td>{{ $value->quantity }}</td>
            <td>PHP {{ number_format($value->amount,2,'.',',') }}</td>
            <td>PHP {{ number_format($value->total_amount,2,'.',',') }}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </center>

    <!-- Text input-->
    <!-- <div class="form-group">
      <label class="col-md-4 control-label" for="background_color">Background Color</label>
      <div class="col-md-4">
        <div class="input-group bgcolor">
        {!! Form::text('background_color', null, ['class'=>'form-control input-md']) !!}
          <span class="input-group-addon"><i style="border: 1px solid #cccccc"></i></span>
        </div>
      </div>
      <script>
          $(function(){
              $('.bgcolor').colorpicker();
          });
      </script>
    </div> -->


    </fieldset>

</div>

resources/views/checkout/index.blade.php
@extends('app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            {!! Breadcrumbs::render() !!}
            <div class="panel panel-default">
                <div class="panel-heading">ORDER MANAGEMENT</div>
                <div class="panel-body">
                    <div class="row paging">
                        <div class="col-md-6">
                            @if (isset($query))
                                {!! $items->appends(['q'=>$query])->render() !!}
                            @else
                                {!! $items->render() !!}
                            @endif
                        </div>
                        <div class="col-md-6 text-right">
                            <!-- <a href="{{ route('admin.items.create') }}" class="btn btn-primary">Add Item</a> -->
                        </div>
                    </div>

                    <div id="custom-search-input" class="paging">
                        {!! Form::open([ 'method' => 'GET', 'route' => 'admin.checkout.search' ]) !!}
                        <div class="input-group col-md-12">
                        {!! Form::text('q', null, ['class'=>'form-control input-xs', 'placeholder'=>'Search Order #']) !!}
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-xs" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </span>
                        </div>
                        {!! Form::close() !!}
                    </div>

                    @if ($items->isEmpty())
                        <p class="alert alert-danger">No items found</p>
                    @else

                    <table class="table table-responsive">
                        <tr>
                            <th>Order ID</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th></th>
                        </tr>

                        @foreach ($items as $item)
                        <tr>
                            <td>{!! $item['order_id'] !!}</td>
                            <td>PHP {!! number_format($item['amount'], 2, '.', ',') !!}</td>
                            <td><span class="label {{ ($item['o_status'] == 'New' ? 'label-success' : ($item['o_status'] == 'Cancelled' ? 'label-danger' : 'label-primary')) }}">{!! $item['o_status'] !!}</span></td>
                            <td class="text-right">
                                <a href="{{ route('admin.checkout.show', [$item]) }}" class="btn btn-default btn-xs"
                                    data-toggle="tooltip" data-placement="top" title="View">
                                    <span class="glyphicon glyphicon-eye-open"></span>
                                </a>
                                <a href="{{ route('admin.checkout.edit', [$item]) }}" class="btn btn-default btn-xs"
                                    data-toggle="tooltip" data-placement="top" title="Edit">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                                <a href="{{ route('admin.checkout.destroy', [$item]) }}" class="btn btn-default btn-xs btn-danger delete-confirm"
                                        data-toggle="tooltip" data-placement="top" title="Delete">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            </td>
                        </tr>

                        @endforeach
                    </table>
                    @endif

                    <div class="row paging">
                        <div class="col-md-6">
                            @if (isset($query))
                                {!! $items->appends(['q'=>$query])->render() !!}
                            @else
                                {!! $items->render() !!}
                            @endif
                        </div>
                        <div class="col-md-6 text-right">
                            <!-- <a href="{{ route('admin.items.create') }}" class="btn btn-primary">Add Item</a> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/checkout/show.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                {!! Breadcrumbs::render() !!}
                <div class="panel panel-default">
                    <div class="panel-heading">VIEW ITEM</div>

                    <div class="panel-body">

                        <div class="row">
                            <div class="col-md-12">
                                <h2>{{ $item['type_name'] }}</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Texture:</h4>
                                <p class="text-center">
                                    @foreach ($item['items'] as $key => $value)
                                    <img src="/uploads/products/{{ $value->product_id }}.svg" style="max-width: 100%;">
                                    <?php break; ?>
                                    @endforeach
                                </p>
                            </div>
                            <div class="col-md-6">
                                <h4>Order Status:</h4>
                                <p><span class="label {{ ($item['o_status'] == 'New' ? 'label-success' : 'label-primary') }}">{!! $item['o_status'] !!}</span></p>
                                <h4>Order #:</h4>
                                <p>{!! $item['order_id'] !!}</p>
                                <h4>Amount</h4>
                                <p>PHP {!! number_format($item['amount'],2,'.',',') !!}</p>
                                <h4>Payment Mode:</h4>
                                <p>{!! ($item['payment_mode'] == 1 ? "CASH" : "CHEQUE") !!}</p>
                                <h4>Order Items:</h4>
                                <dl class="dl-horizontal">

                                    @foreach ($item['items'] as $key => $value)
                                    <dt>Product Title: </dt>
                                    <dd>{{ App\Product::find($value->product_id)->title }}</dd>
                                    <?php break; ?>
                                    @endforeach
                                    @foreach ($item['items'] as $key => $value)
                                        <dt>Size: </dt>
                                        <dd>{{ $value->size }} {{ $value->country_size }}</dd>
                                        <dt>Quantity: </dt>
                                        <dd>{{ $value->quantity }}</dd>
                                        <dt>Amount: </dt>
                                        <dd>PHP {{ number_format($value->amount,2,'.',',') }}</dd>
                                        <dt>Total Amount: </dt>
                                        <dd>PHP {{ number_format($value->total_amount,2,'.',',') }}</dd>
                                        <br>
                                    @endforeach
                                </dl>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 text-right">
                                <a href="{{ route('admin.checkout.edit', [$item['id']]) }}" class="btn btn-primary">Edit</a>
                                <a href="{{ route('admin.checkout.index') }}" class="btn btn-primary">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection